snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: redis://redis
    doctrine:
      type: predis
      alias: doctrine
      dsn: redis://redis
  doctrine:
    metadata_cache:
      client: doctrine
      entity_manager: default
      document_manager: default
    result_cache:
      client: doctrine
      entity_manager: default
    query_cache:
      client: doctrine
      entity_manager: default