version: '2'

services:
    db:
      restart: always
      image: mysql:5.7
      container_name: mysql
      env_file:
      - .env
      ports:
        - "3306:3306"
      environment:
        - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        - "MYSQL_USER=${MYSQL_USER}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        - "MYSQL_DATABASE=${MYSQL_DATABASE}"
    web:
      restart: always
      image: nginx:latest
      container_name: web
      ports:
        - "8080:80"
      volumes:
        - .:/api
        - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      links:
        - php_server:php
    php_server:
      restart: always
      container_name: sf4
      build: ./docker/php
      volumes:
        - .:/api
      links:
        - db:db